PCBuild/KillerApp/Controllers/PCBuildController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Dapper;
using KillerApp.Domain;
using KillerApp.Factory;
using KillerApp.Logic.Interfaces;
using KillerApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace KillerApp.Controllers
{
    public class PcBuildController : Controller
    {
        private readonly IPcBuildLogic _pcBuildLogic;
        private readonly ILikeLogic _likeLogic;

        private List<PcPart> _parts = new List<PcPart>();

        #region HttpGetMethods

        public PcBuildController(IConfiguration configuration)
        {
            _pcBuildLogic = PcBuildFactory.CreateLogic(configuration);
            _likeLogic = LikeFactory.CreateLogic(configuration);
        }

        public IActionResult Index(bool newBuild = false)
        {
            if(newBuild)
                HttpContext.Session.Clear();

            var build = new Build();
            var selectedPcParts = new List<PcPart>();

            if (HttpContext.Session.Keys.Any())
            {
                if (HttpContext.Session.Keys.Contains("Build"))
                    build = GetBuild();

                selectedPcParts = GetSelectedPcParts();
            }

            if (!build.Finished)
            {
                if (selectedPcParts.Count != 0)
                    _parts = _pcBuildLogic.GetPartsByType(build, selectedPcParts.Last()._Type).AsList();
                else
                    _parts = _pcBuildLogic.GetPartsByType(build, PcPart.PcType.Null).AsList();

                var partsObject = _parts;
                HttpContext.Session.SetString("Parts", JsonConvert.SerializeObject(partsObject));
            }

            int progress = 0;
            if (selectedPcParts.Count() != 0)
                progress = _pcBuildLogic.GetProgress(selectedPcParts.Last()._Type);

            var model = new PcBuildIndexViewModel
            {
                PcParts = _parts,
                SelectedPcParts = selectedPcParts,
                BuildFinished = build.Finished,
                Progress = progress
            };

            return View(model);
        }

        public IActionResult Result()
        {
            var websites = _pcBuildLogic.GetWebsites();

            IEnumerable <Result> pcParts = _pcBuildLogic.GetPrices(GetSelectedPcParts(), websites);
            var model = new PcBuildResultViewModel
            {
                PcParts = pcParts,
                BestOption = _pcBuildLogic.CheckBestPriceOption(pcParts.AsList())
            };
            return View(model);
        }

        public IActionResult Detail(string buildId)
        {
            PcBuildDetailViewModel model = new PcBuildDetailViewModel
            {
                Build = _pcBuildLogic.GetBuild(buildId),
                Account = _pcBuildLogic.GetUserFromBuild(buildId)
            };

            if (User.Identity is ClaimsIdentity claimsIdentity && User.Identity.IsAuthenticated)
            {
                var userId = GetUserId();

                model.Liked = _likeLogic.GetLikeFromUser(buildId, userId);
                model.Disliked = _likeLogic.GetDislikeFromUser(buildId, userId);
            }
            model.Build.Id = buildId;

            return View(model);
        }

        [Authorize(Policy = "Moderator")]
        public IActionResult Add()
        {
            var model = new PcBuildAddViewModel(_pcBuildLogic.GetProperties().AsList(),
                _pcBuildLogic.GetAllTypes().AsList());
            return View(model);
        }

        #endregion

        #region PrivateMethods

        private List<PcPart> GetSelectedPcParts()
        {
            var selectedPcParts = new List<PcPart>();
            var types = _pcBuildLogic.GetAllTypes().AsList();

            foreach (var type in types)
                if (HttpContext.Session.TryGetValue(type.ToString(), out var value))
                    selectedPcParts.Add(JsonConvert.DeserializeObject<PcPart>(HttpContext.Session.GetString(type.ToString())));

            return selectedPcParts;
        }

        private Build GetBuild()
        {
            var buildObject = HttpContext.Session.GetString("Build");

            Build build = new Build();
            if(buildObject != null)
            {
                build = JsonConvert.DeserializeObject<Build>(buildObject);
            }
            return build;
        }

        private void AddBuild(Build build)
        {
            var builObject = build;
            HttpContext.Session.SetString("Build", JsonConvert.SerializeObject(builObject));
        }

        private string GetUserId()
        {
            var claimsIdentity = User.Identity as ClaimsIdentity;
            return claimsIdentity.FindFirst("UserId").Value;
        }

        #endregion

        #region HttpPost Methods

        [HttpPost]
        public IActionResult SendPcPart(PcBuildIndexViewModel viewModel)
        {
            var parts = HttpContext.Session.GetString("Parts");
            var _parts = JsonConvert.DeserializeObject<List<PcPart>>(parts);

            var pcPart = _parts.Find(PcPart => PcPart.Id == viewModel.SelectedPcPartId);
            HttpContext.Session.SetString(pcPart._Type.ToString(), JsonConvert.SerializeObject(pcPart));

            var build = GetBuild();
            if(build != null)
                build = _pcBuildLogic.AddBuild(build, pcPart);

            AddBuild(build);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> AddPcPart(PcBuildAddViewModel viewModel)
        {
            if (viewModel.PcPart.Image != null)
            {
                var path = Path.Combine
                (
                    Directory.GetCurrentDirectory(),
                    "wwwroot",
                    "images",
                    viewModel.PcPart.Image.FileName
                );

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await viewModel.PcPart.Image.CopyToAsync(stream);
                }
                _pcBuildLogic.AddPcPart(viewModel.Properties, viewModel.PcPart, viewModel.PcPart.Image.FileName);
            }
            else
            {
                _pcBuildLogic.AddPcPart(viewModel.Properties, viewModel.PcPart);
            }

            return RedirectToAction("Add");
        }

        [Authorize]
        [HttpPost]
        public IActionResult SaveBuild(PcBuildResultViewModel viewModel)
        {
            var userId = GetUserId();

            _pcBuildLogic.SetBuild(viewModel.PcBuild, GetSelectedPcParts(), userId);
            return RedirectToAction("Result");
        }

        [HttpPost]
        public IActionResult ChangeLikeStatus(PcBuildDetailViewModel viewModel)
        {
            var userId = GetUserId();

            if(viewModel.Liked)
                _likeLogic.SubmitLike(viewModel.Build, userId);
            else
                _likeLogic.SubmitDislike(viewModel.Build, userId);

            return RedirectToAction("Detail", viewModel.Build.Id);
        }

        #endregion
    }
}

PCBuild/KillerApp/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - KillerApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/css/site.css"/>
        <link href="~/css/multi-select.css" media="screen" rel="stylesheet" type="text/css">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
    </environment>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-right">
            <ul class="nav navbar-nav navbar-corner-right">
                <li>
                    <a class="hvr-underline-from-center" id="accountLink" asp-area="" asp-controller="Account" asp-action="Overview">ACCOUNT</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand hvr-underline-from-center">PCBuild - tool</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a class="hvr-underline-from-center" asp-area="" asp-controller="PcBuild" asp-action="Index">PC SAMENSTELLEN</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="AccountPopUp" id="PopUp">
    <div class="glyphicon glyphicon-triangle-top PopUpIcon"></div>
    @if (User.Identity.IsAuthenticated)
    {
        var claimsIdentity = User.Identity as ClaimsIdentity;
        if (claimsIdentity != null)
        {
            var name = claimsIdentity.FindFirst("Username").Value;
            <h4>@name.ToUpper()</h4>
        }
        <form asp-area="" asp-controller="Account" asp-action="LogOut" class="PopUpBottom">
            <div class="PopUpBottom">
                <div class="NoAccount">
                    <a class="btn btn-1 btn-small" asp-area="" asp-controller="Account" asp-action="Overview">ACCOUNT OVERZICHT</a>
                </div>
                <div class="PopUpButtonContainer">
                    <button class="btn btn-1 btn-small">
                        <span>Log out</span>
                    </button>
                </div>
            </div>
        </form>
    }
    else
    {
        <h4>Inloggen:</h4>
        <p>Accountnaam: </p>
        <form asp-area="" asp-controller="Account" asp-action="LogIn">
            <input class="form-control" type="text" id="loginUserName" name="userName"/>
            <p>Wachtwoord: </p>
            <input class="form-control" type="password" id="loginPassword" name="password"/>
            <br/>
            <p class="NoAccount-p">Heb je nog geen account?</p>
            <div class="PopUpBottom">
                <div class="NoAccount">
                    <a class="btn btn-1 btn-small" asp-area="" asp-controller="Account" asp-action="Create">account aanmaken</a>
                </div>
                <div class="PopUpButtonContainer">
                    <button class="btn btn-1 btn-small">
                        <span>Log in</span>
                    </button>
                </div>
            </div>
        </form>
    }
</div>
<div class="container body-content">
    @RenderBody()
</div>
<div class="footer-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <h4>&copy; 2018 - KillerApp</h4>
            </div>
            <div class="col-sm-6">
                <h2>Informatie:</h2>
                <p>website@gmail.com</p>
                <p>06 000 000 00</p>
            </div>
        </div>
    </div>
</div>

<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/AJAXCalls.js" asp-append-version="true"></script>
    <script src="~/js/Site.js" asp-append-version="true"></script>
    <script src="~/js/partialViewRenderer.js" asp-append-version="true"></script>
    <script src="~/js/jquery.multi-select.js" type="text/javascript"></script>
</environment>
<environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <script src="~/js/AJAXCalls.min.js" asp-append-version="true"></script>
    <script src="~/js/Site.min.js" asp-append-version="true"></script>
    <script src="~/js/partialViewRenderer.min.js" asp-append-version="true"></script>
</environment>

@RenderSection("Scripts", false)
</body>
</html>